package effect;

public enum EffectType{
    CHANGE_ATK_STAT,
    CHANGE_DEF_STAT,
    CHANGE_EVD_STAT,
    ADD_DICE_COUNT,
    MULTYPLY_DICE_COUNT,
    CHANGE_DICE_RESULT,
    CHANGE_DAMAGE_GIVEN,
    CHANGE_DAMAGE_TAKEN
}
